services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
